services:
  kkallong-next:
    build:
      context: .
    image: python3.14.2:trixie-slim-uv-bun
    container_name: kkallong-next
    tty: true
    ipc: host
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/root/kkallong-next
      - /tmp/.X11-unix:/tmp/.X11-unix

  kkallong-next-gpu:
    extends:
      service: kkallong-next
    container_name: kkallong-next-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - gpu
